language: android

jdk: 
  - oraclejdk8
  - oraclejdk11
android: 
  components: 
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-support
  - extra-android-m2repository 
  - extra-google-m2repository
  licenses: 
  - ".+"

before_install:
  - chmod +x ./gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
 

  
