language: android


android: 
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-26
  licenses: 
  - ".+"

before_install:
  - chmod +x ./gradlew
 
 
script: 
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew build 
  
branches: 
  only: 
  - master
  
